on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubunut-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test:blueprint
